/* Generated By:JavaCC: Do not edit this line. TransformLangParserTreeConstants.java Version 5.0 */
package org.jetel.ctl;

public interface TransformLangParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTARTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTIMPORTSOURCE = 3;
  public int JJTPARAMETERS = 4;
  public int JJTTYPE = 5;
  public int JJTFUNCTIONDECLARATION = 6;
  public int JJTVARIABLEDECLARATION = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTCONDITIONALEXPRESSION = 9;
  public int JJTOR = 10;
  public int JJTAND = 11;
  public int JJTCOMPARISON = 12;
  public int JJTADDNODE = 13;
  public int JJTSUBNODE = 14;
  public int JJTMULNODE = 15;
  public int JJTDIVNODE = 16;
  public int JJTMODNODE = 17;
  public int JJTUNARYSTATEMENT = 18;
  public int JJTUNARYNONSTATEMENT = 19;
  public int JJTPOSTFIXEXPRESSION = 20;
  public int JJTMEMBERACCESSEXPRESSION = 21;
  public int JJTARRAYACCESSEXPRESSION = 22;
  public int JJTINFUNCTION = 23;
  public int JJTFUNCTIONCALL = 24;
  public int JJTISNULLNODE = 25;
  public int JJTNVLNODE = 26;
  public int JJTNVL2NODE = 27;
  public int JJTIIFNODE = 28;
  public int JJTPRINTERRNODE = 29;
  public int JJTPRINTLOGNODE = 30;
  public int JJTPRINTSTACKNODE = 31;
  public int JJTRAISEERRORNODE = 32;
  public int JJTREADDICTNODE = 33;
  public int JJTWRITEDICTNODE = 34;
  public int JJTDELETEDICTNODE = 35;
  public int JJTFIELDACCESSEXPRESSION = 36;
  public int JJTIDENTIFIER = 37;
  public int JJTARGUMENTS = 38;
  public int JJTDATEFIELD = 39;
  public int JJTLOGLEVEL = 40;
  public int JJTLITERAL = 41;
  public int JJTLISTOFLITERALS = 42;
  public int JJTBLOCK = 43;
  public int JJTIFSTATEMENT = 44;
  public int JJTSWITCHSTATEMENT = 45;
  public int JJTCASESTATEMENT = 46;
  public int JJTWHILESTATEMENT = 47;
  public int JJTFORSTATEMENT = 48;
  public int JJTFOREACHSTATEMENT = 49;
  public int JJTDOSTATEMENT = 50;
  public int JJTBREAKSTATEMENT = 51;
  public int JJTCONTINUESTATEMENT = 52;
  public int JJTRETURNSTATEMENT = 53;
  public int JJTSEQUENCENODE = 54;
  public int JJTLOOKUPNODE = 55;


  public String[] jjtNodeName = {
    "Start",
    "StartExpression",
    "void",
    "ImportSource",
    "Parameters",
    "Type",
    "FunctionDeclaration",
    "VariableDeclaration",
    "Assignment",
    "ConditionalExpression",
    "Or",
    "And",
    "Comparison",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "UnaryStatement",
    "UnaryNonStatement",
    "PostfixExpression",
    "MemberAccessExpression",
    "ArrayAccessExpression",
    "InFunction",
    "FunctionCall",
    "IsNullNode",
    "NVLNode",
    "NVL2Node",
    "IIfNode",
    "PrintErrNode",
    "PrintLogNode",
    "PrintStackNode",
    "RaiseErrorNode",
    "ReadDictNode",
    "WriteDictNode",
    "DeleteDictNode",
    "FieldAccessExpression",
    "Identifier",
    "Arguments",
    "DateField",
    "LogLevel",
    "Literal",
    "ListOfLiterals",
    "Block",
    "IfStatement",
    "SwitchStatement",
    "CaseStatement",
    "WhileStatement",
    "ForStatement",
    "ForeachStatement",
    "DoStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "SequenceNode",
    "LookupNode",
  };
}
/* JavaCC - OriginalChecksum=6ef61590ebdf38b5894b97724d8f8fd0 (do not edit this line) */
