/* Generated By:JJTree&JavaCC: Do not edit this line. TransformLangParserConstants.java */
package org.jetel.ctl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TransformLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TL_SHEBANG = 12;
  /** RegularExpression Id. */
  int TL_COMPILE = 13;
  /** RegularExpression Id. */
  int TL_GENERATED = 14;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 15;
  /** RegularExpression Id. */
  int LONG_LITERAL = 16;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 17;
  /** RegularExpression Id. */
  int HEX_LITERAL = 18;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 19;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 20;
  /** RegularExpression Id. */
  int EXPONENT = 21;
  /** RegularExpression Id. */
  int STRING_LITERAL = 22;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 23;
  /** RegularExpression Id. */
  int DATE_LITERAL = 24;
  /** RegularExpression Id. */
  int DATETIME_LITERAL = 25;
  /** RegularExpression Id. */
  int NULL_LITERAL = 26;
  /** RegularExpression Id. */
  int ISNULL = 27;
  /** RegularExpression Id. */
  int NVL = 28;
  /** RegularExpression Id. */
  int NVL2 = 29;
  /** RegularExpression Id. */
  int IIF = 30;
  /** RegularExpression Id. */
  int IN = 31;
  /** RegularExpression Id. */
  int PRINT_ERR = 32;
  /** RegularExpression Id. */
  int PRINT_LOG = 33;
  /** RegularExpression Id. */
  int PRINT_STACK = 34;
  /** RegularExpression Id. */
  int RAISE_ERROR = 35;
  /** RegularExpression Id. */
  int STRING_PLAIN_LITERAL = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int NOT = 39;
  /** RegularExpression Id. */
  int EQUAL = 40;
  /** RegularExpression Id. */
  int NON_EQUAL = 41;
  /** RegularExpression Id. */
  int LESS_THAN = 42;
  /** RegularExpression Id. */
  int LESS_THAN_EQUAL = 43;
  /** RegularExpression Id. */
  int GREATER_THAN = 44;
  /** RegularExpression Id. */
  int GREATER_THAN_EQUAL = 45;
  /** RegularExpression Id. */
  int REGEX_EQUAL = 46;
  /** RegularExpression Id. */
  int REGEX_CONTAINS = 47;
  /** RegularExpression Id. */
  int MINUS = 48;
  /** RegularExpression Id. */
  int PLUS = 49;
  /** RegularExpression Id. */
  int MULTIPLY = 50;
  /** RegularExpression Id. */
  int DIVIDE = 51;
  /** RegularExpression Id. */
  int MODULO = 52;
  /** RegularExpression Id. */
  int INCR = 53;
  /** RegularExpression Id. */
  int DECR = 54;
  /** RegularExpression Id. */
  int TILDA = 55;
  /** RegularExpression Id. */
  int ASSIGN = 56;
  /** RegularExpression Id. */
  int MAPPING = 57;
  /** RegularExpression Id. */
  int SEMICOLON = 58;
  /** RegularExpression Id. */
  int BLOCK_START = 59;
  /** RegularExpression Id. */
  int BLOCK_END = 60;
  /** RegularExpression Id. */
  int OPEN_PAR = 61;
  /** RegularExpression Id. */
  int CLOSE_PAR = 62;
  /** RegularExpression Id. */
  int DOT = 63;
  /** RegularExpression Id. */
  int QUESTION_MARK = 64;
  /** RegularExpression Id. */
  int COLON = 65;
  /** RegularExpression Id. */
  int ASSIGN_PLUS = 66;
  /** RegularExpression Id. */
  int ASSIGN_MINUS = 67;
  /** RegularExpression Id. */
  int ASSIGN_MULTIPLY = 68;
  /** RegularExpression Id. */
  int ASSIGN_DIVIDE = 69;
  /** RegularExpression Id. */
  int ASSIGN_MODULO = 70;
  /** RegularExpression Id. */
  int INT_VAR = 71;
  /** RegularExpression Id. */
  int LONG_VAR = 72;
  /** RegularExpression Id. */
  int DATE_VAR = 73;
  /** RegularExpression Id. */
  int DOUBLE_VAR = 74;
  /** RegularExpression Id. */
  int DECIMAL_VAR = 75;
  /** RegularExpression Id. */
  int BOOLEAN_VAR = 76;
  /** RegularExpression Id. */
  int STRING_VAR = 77;
  /** RegularExpression Id. */
  int BYTE_VAR = 78;
  /** RegularExpression Id. */
  int LIST_VAR = 79;
  /** RegularExpression Id. */
  int MAP_VAR = 80;
  /** RegularExpression Id. */
  int RECORD_VAR = 81;
  /** RegularExpression Id. */
  int OBJECT_VAR = 82;
  /** RegularExpression Id. */
  int VOID_VAR = 83;
  /** RegularExpression Id. */
  int BREAK = 84;
  /** RegularExpression Id. */
  int CONTINUE = 85;
  /** RegularExpression Id. */
  int ELSE = 86;
  /** RegularExpression Id. */
  int FOR = 87;
  /** RegularExpression Id. */
  int FOR_EACH = 88;
  /** RegularExpression Id. */
  int FUNCTION = 89;
  /** RegularExpression Id. */
  int IF = 90;
  /** RegularExpression Id. */
  int RETURN = 91;
  /** RegularExpression Id. */
  int WHILE = 92;
  /** RegularExpression Id. */
  int CASE = 93;
  /** RegularExpression Id. */
  int ENUM = 94;
  /** RegularExpression Id. */
  int IMPORT = 95;
  /** RegularExpression Id. */
  int LOAD = 96;
  /** RegularExpression Id. */
  int SWITCH = 97;
  /** RegularExpression Id. */
  int CASE_DEFAULT = 98;
  /** RegularExpression Id. */
  int DO = 99;
  /** RegularExpression Id. */
  int TRY = 100;
  /** RegularExpression Id. */
  int CATCH = 101;
  /** RegularExpression Id. */
  int LOOKUP = 102;
  /** RegularExpression Id. */
  int LOOKUP_NEXT = 103;
  /** RegularExpression Id. */
  int LOOKUP_FOUND = 104;
  /** RegularExpression Id. */
  int LOOKUP_ADMIN = 105;
  /** RegularExpression Id. */
  int SEQUENCE = 106;
  /** RegularExpression Id. */
  int LOGLEVEL_DEBUG = 107;
  /** RegularExpression Id. */
  int LOGLEVEL_INFO = 108;
  /** RegularExpression Id. */
  int LOGLEVEL_WARN = 109;
  /** RegularExpression Id. */
  int LOGLEVEL_ERROR = 110;
  /** RegularExpression Id. */
  int LOGLEVEL_FATAL = 111;
  /** RegularExpression Id. */
  int LOGLEVEL_TRACE = 112;
  /** RegularExpression Id. */
  int DICTIONARY = 113;
  /** RegularExpression Id. */
  int DICT_SEPARATOR = 114;
  /** RegularExpression Id. */
  int DICT_IDENTIFIER = 115;
  /** RegularExpression Id. */
  int YEAR = 116;
  /** RegularExpression Id. */
  int MONTH = 117;
  /** RegularExpression Id. */
  int WEEK = 118;
  /** RegularExpression Id. */
  int DAY = 119;
  /** RegularExpression Id. */
  int HOUR = 120;
  /** RegularExpression Id. */
  int MINUTE = 121;
  /** RegularExpression Id. */
  int SECOND = 122;
  /** RegularExpression Id. */
  int MILLISEC = 123;
  /** RegularExpression Id. */
  int RETURN_OK = 124;
  /** RegularExpression Id. */
  int RETURN_SKIP = 125;
  /** RegularExpression Id. */
  int RETURN_ALL = 126;
  /** RegularExpression Id. */
  int RETURN_STOP = 127;
  /** RegularExpression Id. */
  int FIELD_ACCESS_OPERATOR = 128;
  /** RegularExpression Id. */
  int RECORD_ACCESS_FIRST_PART = 129;
  /** RegularExpression Id. */
  int RECORD_ACCESS_SECOND_PART = 130;
  /** RegularExpression Id. */
  int NUMERIC_ID = 131;
  /** RegularExpression Id. */
  int STRING_ID = 132;
  /** RegularExpression Id. */
  int IDENTIFIER = 133;
  /** RegularExpression Id. */
  int LETTER = 134;
  /** RegularExpression Id. */
  int UNDERSCORE = 135;
  /** RegularExpression Id. */
  int ERROR = 139;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;
  /** Lexical state. */
  int WithinSingleLineComment = 2;
  /** Lexical state. */
  int DictionaryEntrySeparator = 3;
  /** Lexical state. */
  int DictionaryEntryIdentifier = 4;
  /** Lexical state. */
  int WithinFieldIdentifier = 5;
  /** Lexical state. */
  int ExpectingFieldIdentifier = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\n\\r\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"//\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"#CTL2\"",
    "\"#CTL2:COMPILE\"",
    "\"#CTL2:GENERATED\"",
    "<INTEGER_LITERAL>",
    "<LONG_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "<DATE_LITERAL>",
    "<DATETIME_LITERAL>",
    "\"null\"",
    "\"isnull\"",
    "\"nvl\"",
    "\"nvl2\"",
    "\"iif\"",
    "\"in\"",
    "\"printErr\"",
    "\"printLog\"",
    "\"printStack\"",
    "\"raiseError\"",
    "\"\\\'\"",
    "<OR>",
    "<AND>",
    "<NOT>",
    "<EQUAL>",
    "<NON_EQUAL>",
    "<LESS_THAN>",
    "<LESS_THAN_EQUAL>",
    "<GREATER_THAN>",
    "<GREATER_THAN_EQUAL>",
    "<REGEX_EQUAL>",
    "\"?=\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"=\"",
    "\":=\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"?\"",
    "\":\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"integer\"",
    "\"long\"",
    "\"date\"",
    "<DOUBLE_VAR>",
    "\"decimal\"",
    "\"boolean\"",
    "\"string\"",
    "<BYTE_VAR>",
    "\"list\"",
    "\"map\"",
    "\"record\"",
    "\"object\"",
    "\"void\"",
    "\"break\"",
    "\"continue\"",
    "\"else\"",
    "\"for\"",
    "\"foreach\"",
    "\"function\"",
    "\"if\"",
    "\"return\"",
    "\"while\"",
    "\"case\"",
    "\"enum\"",
    "\"import\"",
    "\"load\"",
    "\"switch\"",
    "\"default\"",
    "\"do\"",
    "\"try\"",
    "\"catch\"",
    "\"lookup\"",
    "\"lookup_next\"",
    "\"lookup_found\"",
    "\"lookup_admin\"",
    "\"sequence\"",
    "\"debug\"",
    "\"info\"",
    "\"warn\"",
    "\"error\"",
    "\"fatal\"",
    "\"trace\"",
    "\"dictionary\"",
    "<DICT_SEPARATOR>",
    "<DICT_IDENTIFIER>",
    "\"year\"",
    "\"month\"",
    "\"week\"",
    "\"day\"",
    "\"hour\"",
    "\"minute\"",
    "\"second\"",
    "\"millisec\"",
    "\"OK\"",
    "\"SKIP\"",
    "\"ALL\"",
    "\"STOP\"",
    "<FIELD_ACCESS_OPERATOR>",
    "<RECORD_ACCESS_FIRST_PART>",
    "<RECORD_ACCESS_SECOND_PART>",
    "<NUMERIC_ID>",
    "<STRING_ID>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\"_\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<ERROR>",
  };

}
