/* Generated By:JavaCC: Do not edit this line. TransformLangParserTreeConstants.java Version 5.0 */
package org.jetel.ctl;

public interface TransformLangParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTARTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTIMPORTSOURCE = 3;
  public int JJTPARAMETERS = 4;
  public int JJTTYPE = 5;
  public int JJTFUNCTIONDECLARATION = 6;
  public int JJTVARIABLEDECLARATION = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTCONDITIONALFAILEXPRESSION = 9;
  public int JJTCONDITIONALEXPRESSION = 10;
  public int JJTOR = 11;
  public int JJTAND = 12;
  public int JJTCOMPARISON = 13;
  public int JJTADDNODE = 14;
  public int JJTSUBNODE = 15;
  public int JJTMULNODE = 16;
  public int JJTDIVNODE = 17;
  public int JJTMODNODE = 18;
  public int JJTUNARYSTATEMENT = 19;
  public int JJTUNARYNONSTATEMENT = 20;
  public int JJTPOSTFIXEXPRESSION = 21;
  public int JJTMEMBERACCESSEXPRESSION = 22;
  public int JJTARRAYACCESSEXPRESSION = 23;
  public int JJTINFUNCTION = 24;
  public int JJTFUNCTIONCALL = 25;
  public int JJTISNULLNODE = 26;
  public int JJTNVLNODE = 27;
  public int JJTNVL2NODE = 28;
  public int JJTIIFNODE = 29;
  public int JJTPRINTERRNODE = 30;
  public int JJTPRINTLOGNODE = 31;
  public int JJTPRINTSTACKNODE = 32;
  public int JJTRAISEERRORNODE = 33;
  public int JJTREADDICTNODE = 34;
  public int JJTWRITEDICTNODE = 35;
  public int JJTDELETEDICTNODE = 36;
  public int JJTFIELDACCESSEXPRESSION = 37;
  public int JJTIDENTIFIER = 38;
  public int JJTARGUMENTS = 39;
  public int JJTDATEFIELD = 40;
  public int JJTLOGLEVEL = 41;
  public int JJTLITERAL = 42;
  public int JJTLISTOFLITERALS = 43;
  public int JJTBLOCK = 44;
  public int JJTIFSTATEMENT = 45;
  public int JJTSWITCHSTATEMENT = 46;
  public int JJTCASESTATEMENT = 47;
  public int JJTWHILESTATEMENT = 48;
  public int JJTFORSTATEMENT = 49;
  public int JJTFOREACHSTATEMENT = 50;
  public int JJTDOSTATEMENT = 51;
  public int JJTBREAKSTATEMENT = 52;
  public int JJTCONTINUESTATEMENT = 53;
  public int JJTRETURNSTATEMENT = 54;
  public int JJTSEQUENCENODE = 55;
  public int JJTLOOKUPNODE = 56;


  public String[] jjtNodeName = {
    "Start",
    "StartExpression",
    "void",
    "ImportSource",
    "Parameters",
    "Type",
    "FunctionDeclaration",
    "VariableDeclaration",
    "Assignment",
    "ConditionalFailExpression",
    "ConditionalExpression",
    "Or",
    "And",
    "Comparison",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "UnaryStatement",
    "UnaryNonStatement",
    "PostfixExpression",
    "MemberAccessExpression",
    "ArrayAccessExpression",
    "InFunction",
    "FunctionCall",
    "IsNullNode",
    "NVLNode",
    "NVL2Node",
    "IIfNode",
    "PrintErrNode",
    "PrintLogNode",
    "PrintStackNode",
    "RaiseErrorNode",
    "ReadDictNode",
    "WriteDictNode",
    "DeleteDictNode",
    "FieldAccessExpression",
    "Identifier",
    "Arguments",
    "DateField",
    "LogLevel",
    "Literal",
    "ListOfLiterals",
    "Block",
    "IfStatement",
    "SwitchStatement",
    "CaseStatement",
    "WhileStatement",
    "ForStatement",
    "ForeachStatement",
    "DoStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "SequenceNode",
    "LookupNode",
  };
}
/* JavaCC - OriginalChecksum=1c017091ed99186f894dfdce85b5af68 (do not edit this line) */
