/* Generated By:JJTree: Do not edit this line. CLVFComparison.java */

package org.jetel.interpreter.ASTnode;
import org.jetel.interpreter.ExpParser;
import org.jetel.interpreter.TransformLangParserConstants;
import org.jetel.interpreter.TransformLangParserVisitor;

public class CLVFComparison extends SimpleNode implements TransformLangParserConstants {
	
	public int cmpType;
	
	public CLVFComparison(int id) {
		super(id);
	}
	
	public CLVFComparison(ExpParser p, int id) {
		super(p, id);
	}
	
	/** Accept the visitor. **/
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	 public String toString(){
	      return super.toString()+" - "+TransformLangParserConstants.tokenImage[cmpType];
	  }
}