/* Generated By:JJTree: Do not edit this line. CLVFAnd.java */

package org.jetel.interpreter.ASTnode;

import org.jetel.interpreter.ExpParser;
import org.jetel.interpreter.TransformLangParserVisitor;

public class CLVFImportSource extends SimpleNode {
	
  String sourceToImport;
	
  public CLVFImportSource(int id) {
    super(id);
  }

  public CLVFImportSource(ExpParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public void setSourceToImport(String src){
	  this.sourceToImport=src;
  }
  
  public String getSourceToImport(){
	  return this.sourceToImport;
  }
  
}
