#! /bin/sh
# this script was inspired by practices gained from ant run scripts (http://ant.apache.org/)

# usage 
# clover <engine_arguments> <graph_name.grf> [ - <java_arguments> ]
# example:
# cloverserver -verbose myGraph.grf - -classpath /home/name/myTransformation

#split command-line arguments to two sets - clover and jvm arguments
#and define CLOVER_HOME variable
. commonlib $@

${CLOVER_HOME}/bin/clover -noJMX -config ${CLOVER_HOME}/bin/serverProperties $clover_exec_args - -server -Xmx512M -XX:+UseParallelGC $java_exec_args
