/* Generated By:JJTree: Do not edit this line. CLVFIdentifier.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.TransformLangParser;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFIdentifier extends SimpleNode {

	private String name;
	private CLVFVariableDeclaration variable;
	private int blockOffset;
	private int variableOffset;
	
	public CLVFIdentifier(int id) {
		super(id);
	}

	public CLVFIdentifier(TransformLangParser p, int id) {
		super(p, id);
	}

	
	public CLVFIdentifier(CLVFIdentifier node) {
		super(node);
		this.name = node.name;
		this.variable = node.variable;
	}

	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getName() {
		// this piece of code makes prefixing of variables in the AST post processing step possible
		return (variable != null) ? variable.getName() : name;
	}
	
	public void setBlockOffset(int blockOffset) {
		this.blockOffset = blockOffset;
	}
	
	public int getBlockOffset() {
		return blockOffset;
	}
	
	public void setVariableOffset(int variableOffset) {
		this.variableOffset = variableOffset;
	}
	
	public int getVariableOffset() {
		return variableOffset;
	}
	
	@Override
	public String toString() {
		return super.toString() + " " + "\"" + name  + "\"";
	}

	public void setVariable(CLVFVariableDeclaration variable) {
		this.variable = variable;
	}
	
	public CLVFVariableDeclaration getVariable() {
		return variable;
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFIdentifier(this);
	}
}
