/* Generated By:JJTree: Do not edit this line. CLVFNVLNode.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.ExpParser;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFNVLNode extends SimpleNode {
	public CLVFNVLNode(int id) {
		super(id);
	}

	public CLVFNVLNode(ExpParser p, int id) {
		super(p, id);
	}

	public CLVFNVLNode(CLVFNVLNode node) {
		super(node);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFNVLNode(this);
	}
}
