/* Generated By:JJTree: Do not edit this line. CLVFAnd.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.ExpParser;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFAnd extends SimpleNode {
	public CLVFAnd(int id) {
		super(id);
	}

	public CLVFAnd(ExpParser p, int id) {
		super(p, id);
	}

	public CLVFAnd(CLVFAnd node) {
		super(node);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFAnd(this);
	}
}
