/* Generated By:JJTree: Do not edit this line. CLVFInFunction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=CLVF,NODE_EXTENDS=,NODE_FACTORY= */
package org.jetel.ctl.ASTnode;

import org.jetel.ctl.TransformLangParser;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFInFunction extends SimpleNode {
	public CLVFInFunction(int id) {
		super(id);
	}

	public CLVFInFunction(TransformLangParser p, int id) {
		super(p, id);
	}

	public CLVFInFunction(CLVFInFunction node) {
		super(node);
	}
	
	/** Accept the visitor. **/
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFInFunction(this);
	}
}
