/* Generated By:JJTree: Do not edit this line. CLVFModNode.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.ExpParser;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFModNode extends SimpleNode {


	public CLVFModNode(int id) {
		super(id);
	}

	public CLVFModNode(ExpParser p, int id) {
		super(p, id);
	}

	public CLVFModNode(CLVFModNode node) {
		super(node);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFModNode(this);
	}
}
