/* Generated By:JJTree: Do not edit this line. CLVFVarDeclaration.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.ExpParser;
import org.jetel.ctl.TransformLangParserConstants;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFVariableDeclaration extends SimpleNode implements TransformLangParserConstants {

	private int variableOffset;
	private int blockOffset;
	private String name;

	public CLVFVariableDeclaration(int id) {
		super(id);
	}

	public CLVFVariableDeclaration(ExpParser p, int id) {
		super(p, id);
	}

	public CLVFVariableDeclaration(CLVFVariableDeclaration node) {
		super(node);
		this.name = node.name;
	}

	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public void setName(String name) {
		this.name = name;
	}

	public String toString() {
		return super.toString() + " name \"" + name + "\"";
	}

	public String getName() {
		return name;
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFVariableDeclaration(this);
	}
	
	public void setVariableOffset(int variableOffset) {
		this.variableOffset = variableOffset;
	}
	
	public int getVariableOffset() {
		return variableOffset;
	}
	
	public void setBlockOffset(int blockOffset) {
		this.blockOffset = blockOffset;
	}
	
	public int getBlockOffset() {
		return blockOffset;
	}
}
