/* Generated By:JJTree: Do not edit this line. CLVFConditionalExpression.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.TransformLangParser;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFConditionalExpression extends SimpleNode {
	
	public CLVFConditionalExpression(int id) {
		super(id);
	}

	public CLVFConditionalExpression(TransformLangParser p, int id) {
		super(p, id);
	}

	
	
	public CLVFConditionalExpression(CLVFConditionalExpression node) {
		super(node);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFConditionalExpression(this);
	}
}
