/* Generated By:JJTree: Do not edit this line. CLVFCaseExpression.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.ExpParser;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFCaseStatement extends SimpleNode {

	boolean isDefaultClause = false;
	
	public CLVFCaseStatement(int id) {
		super(id);
	}

	public CLVFCaseStatement(ExpParser p, int id) {
		super(p, id);
	}

	
	
	public CLVFCaseStatement(CLVFCaseStatement node) {
		super(node);
		this.isDefaultClause = node.isDefaultClause;
	}

	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	public boolean isDefaultCase() {
		// default case statement has no condition, only body/statement as its child
		return isDefaultClause;
	}
	
	public void setDefaultClause(boolean isDefaultClause) {
		this.isDefaultClause = isDefaultClause;
	}

	@Override
	public SimpleNode duplicate() {
		return new CLVFCaseStatement(this);
	}
	
}
