/* Generated By:JJTree: Do not edit this line. CLVFStart.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.ExpParser;
import org.jetel.ctl.TransformLangParserVisitor;
import org.jetel.ctl.data.Scope;

public class CLVFStartExpression extends SimpleNode {

	private Scope scope;
	private boolean compiledMode = false;
	
	public CLVFStartExpression(int id) {
		super(id);
	}

	public CLVFStartExpression(ExpParser p, int id) {
		super(p, id);
	}

	public CLVFStartExpression(CLVFStartExpression node) {
		super(node);
		this.scope = node.scope;
	}

	public void setCompiled(boolean compiled) {
		this.compiledMode = compiled;
	}
	
	public boolean getCompiled() {
		return this.compiledMode;
	}
	
	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	public void setScope(Scope scope) {
		this.scope = scope;
	}
	
	public Scope getScope() {
		return scope;
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFStartExpression(this);
	}
}
