/* Generated By:JJTree: Do not edit this line. CLVFUnaryExpression.java */

package org.jetel.ctl.ASTnode;

import org.jetel.ctl.TransformLangParser;
import org.jetel.ctl.TransformLangParserVisitor;

public class CLVFUnaryExpression extends SimpleNode {

	// One of ++, --, -, not
	private int operator;
	
	public CLVFUnaryExpression(int id) {
		super(id);
	}

	public CLVFUnaryExpression(TransformLangParser p, int id) {
		super(p, id);
	}

	public CLVFUnaryExpression(CLVFUnaryExpression node) {
		super(node);
		this.operator = node.operator;
	}

	/** Accept the visitor. * */
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	public void setOperator(int operator) {
		this.operator = operator;
	}
	
	public int getOperator() {
		return operator;
	}
	
	@Override
	public SimpleNode duplicate() {
		return new CLVFUnaryExpression(this);
	}
}
