/*
*    jETeL/Clover - Java based ETL application framework.
*    Copyright (C) 2002-04  David Pavlis <david_pavlis@hotmail.com>
*    
*    This library is free software; you can redistribute it and/or
*    modify it under the terms of the GNU Lesser General Public
*    License as published by the Free Software Foundation; either
*    version 2.1 of the License, or (at your option) any later version.
*    
*    This library is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU    
*    Lesser General Public License for more details.
*    
*    You should have received a copy of the GNU Lesser General Public
*    License along with this library; if not, write to the Free Software
*    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*
*/
package org.jetel.connection.jdbc.specific.impl;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;

import org.jetel.connection.jdbc.DBConnection;
import org.jetel.connection.jdbc.SQLCloverStatement.QueryType;
import org.jetel.connection.jdbc.specific.conn.MSSQLConnection;
import org.jetel.exception.JetelException;
import org.jetel.metadata.DataFieldMetadata;
import org.jetel.util.string.StringUtils;

/**
 * Informix specific behaviour.
 * 
 * @author Martin Zatopek (martin.zatopek@javlinconsulting.cz)
 *         (c) Javlin Consulting (www.javlinconsulting.cz)
 *
 * @created Jun 3, 2008
 */
public class InformixSpecific extends AbstractJdbcSpecific {

	private static final InformixSpecific INSTANCE = new InformixSpecific();
	
	protected InformixSpecific() {
		super(AutoGeneratedKeysType.SINGLE);
	}

	public static InformixSpecific getInstance() {
		return INSTANCE;
	}

	/* (non-Javadoc)
	 * @see org.jetel.connection.jdbc.specific.impl.AbstractJdbcSpecific#createSQLConnection(org.jetel.connection.jdbc.DBConnection, org.jetel.connection.jdbc.specific.JdbcSpecific.OperationType)
	 */
	@Override
	public Connection createSQLConnection(DBConnection connection, OperationType operationType) throws JetelException {
		//that is intentional usage of MSSQLConnection!!!
		return new MSSQLConnection(connection, operationType);
	}

	public String quoteIdentifier(String identifier) {
		return "\"" + identifier + "\"";
	}

	/**
	 * Informix validation is different because Informix does not support selects in from
	 * clause
	 */
	public String getValidateQuery(String query, QueryType queryType)
			throws SQLException {

		if (queryType.equals(QueryType.SELECT)) {
			return "select * from table(multiset(" + query + ")) wrapper_table where 1=0";
		} else {
			return super.getValidateQuery(query, queryType);
		}

	}

	public String sqlType2str(int sqlType) {
		switch(sqlType) {
		case Types.TIMESTAMP :
		case Types.TIME :
			return "DATETIME";
		case Types.NUMERIC :
			return "FLOAT";
		case Types.BINARY :
		case Types.VARBINARY :
			return "BYTE";
		case Types.BIGINT :
			return "INT8";
		}
		return super.sqlType2str(sqlType);
	}

	@Override
	public String jetelType2sqlDDL(DataFieldMetadata field) {
		int type = jetelType2sql(field);
		switch(type) {
		case Types.BINARY :
		case Types.VARBINARY :
			return sqlType2str(type);
		}
		return super.jetelType2sqlDDL(field);
	}
	
}
