/* Generated By:JJTree: Do not edit this line. CLVFMulNode.java */

package org.jetel.interpreter;

public class CLVFMulNode extends SimpleNode {
  public CLVFMulNode(int id) {
    super(id);
  }

  public CLVFMulNode(FilterExpParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FilterExpParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
