/* Generated By:JJTree: Do not edit this line. CLVFStringArray.java */

package org.jetel.interpreter;

public class CLVFStringArray extends SimpleNode {
  public CLVFStringArray(int id) {
    super(id);
  }

  public CLVFStringArray(FilterExpParser p, int id) {
    super(p, id);
  }

}
