/* Generated By:JJTree: Do not edit this line. CLVFTrimNode.java */

package org.jetel.interpreter;

public class CLVFTrimNode extends SimpleNode {
  public CLVFTrimNode(int id) {
    super(id);
  }

  public CLVFTrimNode(FilterExpParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FilterExpParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
