/* Generated By:JJTree: Do not edit this line. CLVFDateAddNode.java */

package org.jetel.interpreter;
import java.util.Calendar;

public class CLVFDateAddNode extends SimpleNode {
	
	Calendar calendar;
	int calendarField;
	
	public CLVFDateAddNode(int id) {
		super(id);
		calendar=Calendar.getInstance();
	}
	
	public CLVFDateAddNode(FilterExpParser p, int id) {
		super(p, id);
		calendar=Calendar.getInstance();
	}
	
	/** Accept the visitor. **/
	public Object jjtAccept(FilterExpParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	public void setCalendarField(String fieldName){
		if (fieldName.equalsIgnoreCase("year")){
			calendarField=Calendar.YEAR;
		}else if (fieldName.equalsIgnoreCase("month")){
			calendarField=Calendar.MONTH;
		}else if (fieldName.equalsIgnoreCase("week")){
			calendarField=Calendar.WEEK_OF_YEAR;
		}else{
			calendarField=Calendar.DAY_OF_MONTH;
		}
	}
}
