/* Generated By:JJTree: Do not edit this line. FilterExpParserTreeConstants.java */

package org.jetel.interpreter;

public interface FilterExpParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTCOMPARISON = 4;
  public int JJTADDNODE = 5;
  public int JJTSUBNODE = 6;
  public int JJTMULNODE = 7;
  public int JJTDIVNODE = 8;
  public int JJTMODNODE = 9;
  public int JJTMINUSNODE = 10;
  public int JJTNEGATION = 11;
  public int JJTSUBSTRNODE = 12;
  public int JJTUPPERCASENODE = 13;
  public int JJTLOWERCASENODE = 14;
  public int JJTTRIMNODE = 15;
  public int JJTLENGTHNODE = 16;
  public int JJTTODAYNODE = 17;
  public int JJTISNULLNODE = 18;
  public int JJTNVLNODE = 19;
  public int JJTREPLACENODE = 20;
  public int JJTSTR2NUMNODE = 21;
  public int JJTNUM2STRNODE = 22;
  public int JJTLITERAL = 23;
  public int JJTJETELFIELDLITERAL = 24;
  public int JJTREGEXLITERAL = 25;
  public int JJTCONCATNODE = 26;
  public int JJTDATEADDNODE = 27;
  public int JJTDATEDIFFNODE = 28;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Or",
    "And",
    "Comparison",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "MinusNode",
    "Negation",
    "SubStrNode",
    "UppercaseNode",
    "LowercaseNode",
    "TrimNode",
    "LengthNode",
    "TodayNode",
    "IsNullNode",
    "NVLNode",
    "ReplaceNode",
    "Str2NumNode",
    "Num2StrNode",
    "Literal",
    "JetelFieldLiteral",
    "RegexLiteral",
    "ConcatNode",
    "DateAddNode",
    "DateDiffNode",
  };
}
