/* Generated By:JJTree: Do not edit this line. C:\projects\eclipse\workspace\svn_clover_engine\src\org\jetel\interpreter\TransformLangParserTreeConstants.java */

package org.jetel.interpreter;

public interface TransformLangParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTARTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTFUNCTIONDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTMAPPING = 6;
  public int JJTOR = 7;
  public int JJTAND = 8;
  public int JJTCOMPARISON = 9;
  public int JJTADDNODE = 10;
  public int JJTSUBNODE = 11;
  public int JJTMULNODE = 12;
  public int JJTDIVNODE = 13;
  public int JJTMODNODE = 14;
  public int JJTMINUSNODE = 15;
  public int JJTPLUSPLUSNODE = 16;
  public int JJTMINUSMINUSNODE = 17;
  public int JJTNEGATION = 18;
  public int JJTLITERAL = 19;
  public int JJTINPUTFIELDLITERAL = 20;
  public int JJTGLOBALPARAMETERLITERAL = 21;
  public int JJTVARIABLELITERAL = 22;
  public int JJTREGEXLITERAL = 23;
  public int JJTBLOCK = 24;
  public int JJTSTATEMENTEXPRESSION = 25;
  public int JJTIFSTATEMENT = 26;
  public int JJTSWITCHSTATEMENT = 27;
  public int JJTCASEEXPRESSION = 28;
  public int JJTWHILESTATEMENT = 29;
  public int JJTFORSTATEMENT = 30;
  public int JJTDOSTATEMENT = 31;
  public int JJTBREAKSTATEMENT = 32;
  public int JJTCONTINUESTATEMENT = 33;
  public int JJTRETURNSTATEMENT = 34;
  public int JJTFUNCTIONCALLSTATEMENT = 35;
  public int JJTSUBSTRNODE = 36;
  public int JJTUPPERCASENODE = 37;
  public int JJTLOWERCASENODE = 38;
  public int JJTTRIMNODE = 39;
  public int JJTLENGTHNODE = 40;
  public int JJTTODAYNODE = 41;
  public int JJTISNULLNODE = 42;
  public int JJTNVLNODE = 43;
  public int JJTREPLACENODE = 44;
  public int JJTSTR2NUMNODE = 45;
  public int JJTNUM2STRNODE = 46;
  public int JJTIFFNODE = 47;
  public int JJTPRINTERRNODE = 48;
  public int JJTPRINTSTACKNODE = 49;
  public int JJTBREAKPOINTNODE = 50;
  public int JJTCONCATNODE = 51;
  public int JJTDATEADDNODE = 52;
  public int JJTDATEDIFFNODE = 53;
  public int JJTDATE2STRNODE = 54;
  public int JJTSTR2DATENODE = 55;


  public String[] jjtNodeName = {
    "Start",
    "StartExpression",
    "void",
    "FunctionDeclaration",
    "VarDeclaration",
    "Assignment",
    "Mapping",
    "Or",
    "And",
    "Comparison",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "MinusNode",
    "PlusPlusNode",
    "MinusMinusNode",
    "Negation",
    "Literal",
    "InputFieldLiteral",
    "GlobalParameterLiteral",
    "VariableLiteral",
    "RegexLiteral",
    "Block",
    "StatementExpression",
    "IfStatement",
    "SwitchStatement",
    "CaseExpression",
    "WhileStatement",
    "ForStatement",
    "DoStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "FunctionCallStatement",
    "SubStrNode",
    "UppercaseNode",
    "LowercaseNode",
    "TrimNode",
    "LengthNode",
    "TodayNode",
    "IsNullNode",
    "NVLNode",
    "ReplaceNode",
    "Str2NumNode",
    "Num2StrNode",
    "IffNode",
    "PrintErrNode",
    "PrintStackNode",
    "BreakpointNode",
    "ConcatNode",
    "DateAddNode",
    "DateDiffNode",
    "Date2StrNode",
    "Str2DateNode",
  };
}
