/* Generated By:JJTree: Do not edit this line. .\TransformLangParserTreeConstants.java */

package org.jetel.interpreter;

public interface TransformLangParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTARTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTFUNCTIONDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTMAPPING = 6;
  public int JJTOR = 7;
  public int JJTAND = 8;
  public int JJTCOMPARISON = 9;
  public int JJTADDNODE = 10;
  public int JJTSUBNODE = 11;
  public int JJTMULNODE = 12;
  public int JJTDIVNODE = 13;
  public int JJTMODNODE = 14;
  public int JJTMINUSNODE = 15;
  public int JJTPLUSPLUSNODE = 16;
  public int JJTMINUSMINUSNODE = 17;
  public int JJTNEGATION = 18;
  public int JJTSIZENODE = 19;
  public int JJTLITERAL = 20;
  public int JJTINPUTFIELDLITERAL = 21;
  public int JJTGLOBALPARAMETERLITERAL = 22;
  public int JJTVARIABLELITERAL = 23;
  public int JJTREGEXLITERAL = 24;
  public int JJTBLOCK = 25;
  public int JJTIFSTATEMENT = 26;
  public int JJTSWITCHSTATEMENT = 27;
  public int JJTCASEEXPRESSION = 28;
  public int JJTWHILESTATEMENT = 29;
  public int JJTFORSTATEMENT = 30;
  public int JJTFOREACHSTATEMENT = 31;
  public int JJTDOSTATEMENT = 32;
  public int JJTBREAKSTATEMENT = 33;
  public int JJTCONTINUESTATEMENT = 34;
  public int JJTRETURNSTATEMENT = 35;
  public int JJTFUNCTIONCALLSTATEMENT = 36;
  public int JJTISNULLNODE = 37;
  public int JJTNVLNODE = 38;
  public int JJTREPLACENODE = 39;
  public int JJTIFFNODE = 40;
  public int JJTTRUNCNODE = 41;
  public int JJTPRINTSTACKNODE = 42;
  public int JJTBREAKPOINTNODE = 43;
  public int JJTRAISEERRORNODE = 44;
  public int JJTDATEADDNODE = 45;
  public int JJTDATEDIFFNODE = 46;
  public int JJTDATE2STRNODE = 47;
  public int JJTSTR2DATENODE = 48;
  public int JJTDATE2NUMNODE = 49;
  public int JJTSTR2NUMNODE = 50;
  public int JJTNUM2STRNODE = 51;
  public int JJTPRINTERRNODE = 52;
  public int JJTPRINTLOGNODE = 53;
  public int JJTSEQUENCENODE = 54;
  public int JJTLOOKUPNODE = 55;


  public String[] jjtNodeName = {
    "Start",
    "StartExpression",
    "void",
    "FunctionDeclaration",
    "VarDeclaration",
    "Assignment",
    "Mapping",
    "Or",
    "And",
    "Comparison",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "MinusNode",
    "PlusPlusNode",
    "MinusMinusNode",
    "Negation",
    "SizeNode",
    "Literal",
    "InputFieldLiteral",
    "GlobalParameterLiteral",
    "VariableLiteral",
    "RegexLiteral",
    "Block",
    "IfStatement",
    "SwitchStatement",
    "CaseExpression",
    "WhileStatement",
    "ForStatement",
    "ForeachStatement",
    "DoStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "FunctionCallStatement",
    "IsNullNode",
    "NVLNode",
    "ReplaceNode",
    "IffNode",
    "TruncNode",
    "PrintStackNode",
    "BreakpointNode",
    "RaiseErrorNode",
    "DateAddNode",
    "DateDiffNode",
    "Date2StrNode",
    "Str2DateNode",
    "Date2NumNode",
    "Str2NumNode",
    "Num2StrNode",
    "PrintErrNode",
    "PrintLogNode",
    "SequenceNode",
    "LookupNode",
  };
}
