/* Generated By:JJTree: Do not edit this line. CLVFStart.java */

package org.jetel.interpreter.node;
import org.jetel.interpreter.ExpParser;
import org.jetel.interpreter.TransformLangParserVisitor;
public class CLVFStartExpression extends SimpleNode {
  public CLVFStartExpression(int id) {
    super(id);
  }

  public CLVFStartExpression(ExpParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
