/* Generated By:JJTree: Do not edit this line. CLVFDateDiffNode.java */

package org.jetel.interpreter.node;

import java.util.Calendar;

import org.jetel.interpreter.ExpParser;
import org.jetel.interpreter.TransformLangParserVisitor;

public class CLVFDate2NumNode extends SimpleNode {
	
    public int calendarField;
    public Calendar calendar;
	
	public CLVFDate2NumNode(int id) {
		super(id);
        calendar=Calendar.getInstance();
	}
	
	public CLVFDate2NumNode(ExpParser p, int id) {
		super(p, id);
        calendar=Calendar.getInstance();
	}
	
	
	/** Accept the visitor. **/
	public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	public void setCalendarField(String fieldName){
		if (fieldName.equalsIgnoreCase("year")){
			calendarField=Calendar.YEAR;
		}else if (fieldName.equalsIgnoreCase("month")){
			calendarField=Calendar.MONTH;
		}else if (fieldName.equalsIgnoreCase("week")){
			calendarField=Calendar.WEEK_OF_YEAR;
		}else if (fieldName.equalsIgnoreCase("day")){
				calendarField=Calendar.DAY_OF_MONTH;
		}else if (fieldName.equalsIgnoreCase("hour")){
		     calendarField=Calendar.HOUR_OF_DAY;
		}else if (fieldName.equalsIgnoreCase("minute")){
		     calendarField=Calendar.MINUTE;
        }else if (fieldName.equalsIgnoreCase("sec") || fieldName.equalsIgnoreCase("second") ){
            calendarField=Calendar.SECOND;
		}else{
            calendarField=Calendar.MILLISECOND;
		}
	}
}
