/* Generated By:JJTree: Do not edit this line. CLVFReplaceNode.java */

package org.jetel.interpreter.node;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.jetel.interpreter.ExpParser;
import org.jetel.interpreter.TransformLangParserVisitor;
public class CLVFReplaceNode extends SimpleNode {
    
    public Pattern pattern;
    public Matcher matcher;
    public Object stored;
    
  public CLVFReplaceNode(int id) {
    super(id);
  }

  public CLVFReplaceNode(ExpParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
