/* Generated By:JJTree: Do not edit this line. CLVFPrintStackNode.java */

package org.jetel.interpreter.node;
import org.jetel.interpreter.ExpParser;
import org.jetel.interpreter.TransformLangParserVisitor;
public class CLVFPrintStackNode extends SimpleNode {
  public CLVFPrintStackNode(int id) {
    super(id);
  }

  public CLVFPrintStackNode(ExpParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TransformLangParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
