//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.03 at 01:29:52 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/dictionary/")
package org.jetel.graph.dictionary.jaxb;
